name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build-and-test:
    name: Lint, Test, Build
    runs-on: ubuntu-latest
    env:
      NEXT_TELEMETRY_DISABLED: '1'
      CI: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('robotics/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: Install dependencies
        working-directory: ./robotics
        run: pnpm install --frozen-lockfile

      - name: Lint
        working-directory: ./robotics
        run: pnpm run lint

      - name: Unit tests
        working-directory: ./robotics
        run: pnpm test -- --ci

      - name: Build
        env:
          CI: true
        working-directory: ./robotics
        run: pnpm run build
        continue-on-error: true

      - name: Install Playwright Browsers
        working-directory: ./robotics
        run: pnpm exec playwright install --with-deps

      - name: E2E tests (Playwright)
        working-directory: ./robotics
        run: pnpm exec playwright test

      - name: Upload Playwright traces on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-traces-and-results
          path: |
            robotics/test-results
            robotics/playwright-report
          if-no-files-found: ignore

