// Auto-generated by sort-i18n-ts.js
// File: src/i18n/locales/de/content.ts
const data = {
  "company": {
    "industry": "Humanoide Robotik / AI‑Software",
    "location": "München, Deutschland",
    "mission": "Robotik als Software: sicher, auditierbar, skalierbar.",
    "name": "SIGMACODE AI GmbH",
    "team": "Kernteam (6 FTE) – Hiring‑Fokus AI/Robotics",
    "vision": "Humanoide AI‑Robotik, die Arbeit messbar sicherer und produktiver macht."
  },
  "market": {
    "sam": "Industrie‑Segmente mit hohem Bedarf: Logistik, Fertigung, Facility & Service – initiale Fokuskorridore mit klarer Zahlungsbereitschaft.",
    "som": "Pilot‑regionen mit Enterprise‑Rollouts (DACH/EU) und Partner‑Ökosystem – skalierbar über App‑Store und Fleet‑Deployments.",
    "tam": "> $40 Mrd. bis 2030 (Service Robotics & Humanoids) – getrieben durch Automatisierung, Reshoring und demografischen Wandel."
  },
  "solution": {
    "agents": "RL/IL‑Agenten (Policy‑Hub): Lernen aus Demos & Simulation.",
    "appstore": "Robot‑App‑Store: zertifizierte Skills, Marketplace & Billing.",
    "integration": "Enterprise‑Integration: ERP/WMS/MES/IoT, Digital Twins.",
    "rass": "Robot‑as‑a‑Service (Subscription + Usage) mit Fleet‑Management.",
    "usp": "Guardrails & Compliance (CE/AI‑Act), Zero‑Downtime‑Deployments."
  }
} as const;

export default data;
